name: PR Maven Build
on:
  pull_request:
    paths:
      - "**.xml"
      - "*.yml"
      - "src/**"
      - "ide-config"

env:
  JAVA_VERSION: 17
  JAVA_DISTRO: temurin
  NATIVE_JAVA_VERSION: 23
  GRAALVM_DIST: graalvm-community
  GH_BOT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
  GH_BOT_NAME: "GitHub Action"

permissions:
  contents: read
  actions: read

jobs:
  metadata:
    uses: ebullient/workflows/.github/workflows/java-snap-metadata.yml@main

  build:
    runs-on: ubuntu-latest
    needs: [metadata]
    outputs:
      cache_key: ${{ steps.data_cache.outputs.cache_key }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ./.github/actions/data-cache
        id: data_cache
        with:
          failIfMissing: true

      - name: Build with Maven
        uses: ebullient/workflows/.github/actions/maven-build@main
        with:
          artifact: ${{ needs.metadata.outputs.artifact }}
          version: ${{ needs.metadata.outputs.snapshot }}
          java-version: ${{ env.JAVA_VERSION }}
          java-distribution: ${{ env.JAVA_DISTRO }}

  native-build:
    runs-on: ubuntu-latest
    needs: [metadata, build]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - uses: ./.github/actions/native-data-cache
        with:
          cache_key: ${{ needs.build.outputs.cache_key }}

      - name: Native build with Maven
        uses: ebullient/workflows/.github/actions/native-build@main
        with:
          artifact: ${{ needs.metadata.outputs.artifact }}
          version: ${{ needs.metadata.outputs.snapshot }}
          native-java-version: ${{ env.NATIVE_JAVA_VERSION }}
          distribution: ${{ env.GRAALVM_DIST }}
          matrix-os: ubuntu-latest

